### ISSUE TITLE
org.apache.iceberg.exceptions.NotAuthorizedException: Not authorized: Unauthorized

### ISSUE THREAD

**Issue by ambaricloud** [lakekeeper/lakekeeper#696]
Using "access-control" docker.
1. Generated user Token from UI
2. Started Spark Session.
3. Able to create tables and load data on S3.
4. After 5 min wait, I ran "select" on table, on same spark session, I got below error. 

Py4JJavaError: An error occurred while calling o44.sql.
: org.apache.iceberg.exceptions.NotAuthorizedException: Not authorized: Unauthorized
	at org.apache.iceberg.rest.ErrorHandlers$DefaultErrorHandler.accept(ErrorHandlers.java:210)
	at org.apache.iceberg.rest.ErrorHandlers$DefaultErrorHandler.accept(ErrorHandlers.java:188)

**Comment by c-thiel** [comment]
@ambaricloud thanks for the issue, you are right, I forgot to extend the token lifetime in this example.
I'll fix it tomorrow.

For now, you can open Keycloak at "localhost:30080" and login as user "admin" with password "admin".
In the top left corner dropdown, select "iceberg" Realm. In the left menu click on "Clients" then select "lakekeeper".  Select the "Advanced" tab on the top, and scroll down to "Advanced settings". Set "Access Token Lifespan" to expires in 1 day. Make sure to save.

I'll make this the default tomorrow.

If you want more details on how Authentication will evolve in the future, I have written up a design document that is currently under review and will hopefully become part of the iceberg docs early next year. You can find it here:
https://docs.google.com/document/d/1buW9PCNoHPeP7Br5_vZRTU-_3TExwLx6bs075gi94xc/edit?tab=t.0#heading=h.hufqidg1ij89

Right now clients like spark and pyiceberg don't support native authorization code flows, which is why we have built-in the workaround via the UI.

**Comment by ambaricloud** [comment]
Working. Thank you.
